production:
  sessions:
    default:
      database: moneymaker_prod
      hosts:
        - localhost:27017
      options:
        consistency: :strong
development:
  sessions:
    default:
      database: moneymaker_dev
      hosts:
        - localhost:27017
      options:
        consistency: :strong
test:
  sessions:
    default:
      database: moneymaker_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

